import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

SYSTEM_PROMPT = """
You are an AI detection assistant. 

Analyze the following text and estimate the probability that it was generated by AI rather than written by a human.

Return ONLY valid JSON in this exact format:
{{"score": 0.XX}}

Do not include markdown, explanations, or code fences.

Where score is a float from 0.0 to 1.0:
- 0.0 = almost certainly human-written
- 1.0 = almost certainly AI-generated
"""


def _score_to_attribution(score: float) -> str:
    if score <= 0.39:
        return "Likely Human-written"
    if score <= 0.69:
        return "Uncertain"
    return "Likely AI-generated"


def groq_detect(text: str) -> dict:
    try:
        response = _client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text}
            ],
            temperature=0,
        )
        raw = response.choices[0].message.content.strip()
        score = float(json.loads(raw)["score"])
        score = max(0.0, min(1.0, score))
    except Exception:
        return {"attribution": "Uncertain", "llm_score": 0.5}

    return {"attribution": _score_to_attribution(score), "llm_score": score}
