import json
import math
import os
import re

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

SYSTEM_PROMPT = """
You are an AI detection assistant. 

Analyze the following text and estimate the probability that it was generated by AI rather than written by a human.

Return ONLY valid JSON in this exact format:
{{"score": 0.XX}}

Do not include markdown, explanations, or code fences.

Where score is a float from 0.0 to 1.0:
- 0.0 = almost certainly human-written
- 1.0 = almost certainly AI-generated
"""


def _score_to_attribution(score: float) -> str:
    if score <= 0.39:
        return "Likely Human-written"
    if score <= 0.69:
        return "Uncertain"
    return "Likely AI-generated"


def groq_detect(text: str) -> dict:
    try:
        response = _client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text}
            ],
            temperature=0,
        )
        raw = response.choices[0].message.content.strip()
        score = float(json.loads(raw)["score"])
        score = max(0.0, min(1.0, score))
    except Exception:
        return {"attribution": "Uncertain", "llm_score": 0.5}

    return {"attribution": _score_to_attribution(score), "llm_score": score}


def calculate_confidence(llm_score: float, stylometric_score: float) -> dict:
    confidence = round((llm_score + stylometric_score) / 2, 4)
    return {"confidence": confidence, "attribution": _score_to_attribution(confidence)}


def stylometric_detect(text: str) -> dict:
    try:
        words = re.findall(r"[a-zA-Z]+", text)
        sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]

        # Sub-score 1: sentence length variation
        if len(sentences) >= 2:
            lengths = [len(s.split()) for s in sentences]
            mean = sum(lengths) / len(lengths)
            std = math.sqrt(sum((l - mean) ** 2 for l in lengths) / len(lengths))
            cv = std / mean if mean > 0 else 0
            sent_score = max(0.0, 1.0 - min(cv, 1.0))
        else:
            sent_score = 0.5

        # Sub-score 2: vocabulary diversity (type-token ratio)
        if len(words) >= 10:
            ttr = len(set(w.lower() for w in words)) / len(words)
            vocab_score = ttr
        else:
            vocab_score = 0.5

        # Sub-score 3: punctuation density
        if words:
            MAX_PUNCT_DENSITY = 0.2
            punct_count = len(re.findall(r"[,;:]", text))
            density = punct_count / len(words)
            punct_score = min(density / MAX_PUNCT_DENSITY, 1.0)
        else:
            punct_score = 0.5

        score = round((sent_score + vocab_score + punct_score) / 3, 4)
        score = max(0.0, min(1.0, score))
    except Exception:
        return {"stylometric_score": 0.5}

    return {"stylometric_score": score}
